added self hosted runner functionality to workflow
syntax error

another one

fixed variable errors

passed secrets as variables

fixed variable declaration

so many issues...

added additional changes

fixed syntax errors

more syntax errors

hopefully fixed syntax

added public ip to terraform and action

fixed env var declare

diff --git a/.github/workflows/verify-dashboards-alerts.yaml b/.github/workflows/verify-dashboards-alerts.yaml
--- a/.github/workflows/verify-dashboards-alerts.yaml
+++ b/.github/workflows/verify-dashboards-alerts.yaml
@@ -1,6 +1,7 @@
 name: Verify Dashboards and Alerts OK
 
-on: push
+on: 
+  push:
     # paths:
     #   # Dashboards
     #   - examples/dashboards/app_developer.json
@@ -12,119 +13,205 @@ on: push
     #   - examples/alerts/slo-latency.yaml
 
 jobs:
+  deploy-register-self-runner:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: hashicorp/setup-terraform@v3
+
+      - name: Initialize Terraform Environment
+        run: terraform init
+
+      - name: Create PEM file
+        run: |
+          echo "${{ secrets.AWS_PEM_KEY }}" > ${{ secrets.AWS_KEY_NAME }}.pem
+          chmod 600 ${{ secrets.AWS_KEY_NAME }}.pem
+
+      - name: Apply Terraform Configuration + Extract Public IP
+        run: |
+          terraform apply -auto-approve -var=aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }} -var=aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} -var=aws_key_name=${{ secrets.AWS_KEY_NAME }}
+          # Get the public IP address of the instance
+          echo "EC2_PUBLIC_IP=$(terraform output instance_public_ip)" >> $GITHUB_ENV
+
+
+      - name: Create PEM file
+        run: |
+          echo "${{ secrets.AWS_PEM_KEY }}" > ${{ secrets.AWS_KEY_NAME }}.pem
+          chmod 600 ${{ secrets.AWS_KEY_NAME }}.pem
+
+      - name: Generate Registration Token
+        id: reg_token
+        run: |
+          REPO_OWNER=${{ github.repository_owner }}
+          REPO_NAME=${{ github.event.repository.name }}
+
+          RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runners/registration-token)
+
+          echo "REGISTRATION_TOKEN=$(echo $RESPONSE | jq -r .token)" >> $GITHUB_ENV
+
+      - name: SSH into EC2 Instance and Register Runner
+        env:
+          REGISTRATION_TOKEN: ${{ env.REGISTRATION_TOKEN }}
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_KEY_NAME }}.pem ec2-user@${{ env.EC2_PUBLIC_IP }} << EOF
+            mkdir actions-runner && cd actions-runner
+            curl -o actions-runner-linux-x64-2.281.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.281.1/actions-runner-linux-x64-2.281.1.tar.gz
+            tar xzf ./actions-runner-linux-x64-2.281.1.tar.gz
+            ./config.sh --url https://github.com/${{ github.repository }} --token $REGISTRATION_TOKEN --unattended --labels self-hosted,linux,aws
+            ./svc.sh install
+            ./svc.sh start
+          EOF
+
   verify-dashboards-alerts:
     name: Verify Dashboards and Alerts OK
+    needs: deploy-register-self-runner
     runs-on: self-hosted
     defaults: 
       run:
         shell: bash
     steps:
-    - uses: actions/checkout@v2
-    - name: Run Quickstart
-      run: |
-        kind delete clusters kuadrant-local
-        kind delete clusters kuadrant-local
+      - uses: actions/checkout@v2
 
-        export ISTIO_INSTALL_SAIL=true
-        alias podman='sudo podman'
+      - name: Run Quickstart
+        run: |
+          kind delete clusters kuadrant-local
+          kind delete clusters kuadrant-local
 
-        cat << 'EOF' > automate_setup.expect
-        #!/usr/bin/expect -f
-        set timeout -1
-        spawn bash hack/quickstart-setup.sh
-        expect "Are you ready to begin? (y/n)"
-        send "y\r"
-        expect "Do you want to set up a DNS provider for use with Kuadrant's DNSPolicy API? (y/n)"
-        send "n\r"
-        expect "Thank you for using Kuadrant! If you have any questions or feedback, please reach out to our community."
-        EOF
-        chmod +x automate_setup.expect
-        ./automate_setup.expect
-    - name: Port forward grafana and check if contains dashboards.
-      run: |
-        # Port forward Grafana
-        kubectl -n monitoring wait --for=condition=available deployment grafana --timeout=600s
-        kubectl -n monitoring port-forward service/grafana 3000:3000 &
-        grafana_process_id=$!
-        echo "Successfully port forwarded Grafana service."
+          export ISTIO_INSTALL_SAIL=true
+          alias podman='sudo podman'
 
-        sleep 1
+          cat << 'EOF' > automate_setup.expect
+          #!/usr/bin/expect -f
+          set timeout -1
+          spawn bash hack/quickstart-setup.sh
+          expect "Are you ready to begin? (y/n)"
+          send "y\r"
+          expect "Do you want to set up a DNS provider for use with Kuadrant's DNSPolicy API? (y/n)"
+          send "n\r"
+          expect "Thank you for using Kuadrant! If you have any questions or feedback, please reach out to our community."
+          EOF
+          chmod +x automate_setup.expect
+          ./automate_setup.expect
 
-        # Make API Call and save response to variable.
-        grafana_api_call=$(curl -u admin:admin http://127.0.0.1:3000/api/search)
+      - name: Port forward grafana and check if contains dashboards.
+        run: |
+          # Port forward Grafana
+          kubectl -n monitoring wait --for=condition=available deployment grafana --timeout=600s
+          kubectl -n monitoring port-forward service/grafana 3000:3000 &
+          grafana_process_id=$!
+          echo "Successfully port forwarded Grafana service."
 
-        # Compare the content in json file with field containing dashboard names
+          sleep 1
 
-        app_developer=$(jq -r '.panels[1].title' examples/dashboards/app_developer.json)
-        business_user=$(jq -r '.panels[1].title' examples/dashboards/business_user.json)
-        platform_engineer=$(jq -r '.panels[1].title' examples/dashboards/platform_engineer.json)
+          # Make API Call and save response to variable.
+          grafana_api_call=$(curl -u admin:admin http://127.0.0.1:3000/api/search)
 
-        declare -a missing_dashboards=()
+          # Compare the content in json file with field containing dashboard names
 
-        if [[ "$grafana_api_call" != *"$app_developer"* ]]; then
-          echo "Grafana does not have $app_developer dashboard."
-          missing_dashboards+=("$app_developer")
-        fi
-        if [[ "$grafana_api_call" != *"$business_user"* ]]; then
-          echo "Grafana does not have $business_user dashboard."
-          missing_dashboards+=("$business_user")
-        fi
-        if [[ "$grafana_api_call" != *"$platform_engineer"* ]]; then
-          echo "Grafana does not have $platform_engineer dashboard."
-          missing_dashboards+=("$platform_engineer")
-        fi
+          app_developer=$(jq -r '.panels[1].title' examples/dashboards/app_developer.json)
+          business_user=$(jq -r '.panels[1].title' examples/dashboards/business_user.json)
+          platform_engineer=$(jq -r '.panels[1].title' examples/dashboards/platform_engineer.json)
 
-        if [[ ${#missing_dashboards[@]} -gt 0 ]]; then
-          echo "Grafana is missing the following dashboards:"
-          printf '%s\n' "${missing_dashboards[@]}"
-          echo "Exiting..."
-          exit 1
-        fi
+          declare -a missing_dashboards=()
 
-        echo "Grafana contains dashboards $app_developer, $business_user and $platform_engineer. Continuing to Prometheus..."
-
-        # Close Grafana port-forward.
-        kill $grafana_process_id
-        echo "Stoppped port forwarding Grafana."
-    - name: Port forward Prometheus and check if contains alert rules.
-      run: |
-        kubectl -n monitoring wait --for=condition=ready pod prometheus-k8s-0 --timeout=600s
-        # Port forward Prometheus
-        kubectl -n monitoring port-forward service/prometheus-k8s 9090:9090 &
-        prometheus_process_id=$!
-        echo "Successfully port forwarded Prometheus service."
-
-        sleep 1
-
-        # Make API Call and save response to variable
-        prometheus_api_call=$(curl http://localhost:9090/api/v1/rules)
-
-        # Compare the content in json file with field containing dashboard names.
-
-        readarray -t prometheusrules_policies_missing_alerts < <(yq e '.spec.groups[].rules[].alert' examples/alerts/prometheusrules_policies_missing.yaml)
-        readarray -t slo_availability_alerts < <(yq e '.spec.groups[].rules[].alert' examples/alerts/slo-availability.yaml)
-        readarray -t slo_latency_alerts < <(yq e '.spec.groups[].rules[].alert' examples/alerts/slo-latency.yaml)
-
-        combined_alerts=("${prometheusrules_policies_missing_alerts[@]}" "${slo_availability_alerts[@]}" "${slo_latency_alerts[@]}")
-
-        declare -a missing_alerts=()
-
-        for alert in "${combined_alerts[@]}"; do
-          if [[ "$prometheus_api_call" != *"$alert"* && "$alert" != "null" ]]; then
-            echo "Prometheus does not have $alert rule."
-            missing_alerts+=("$alert")
+          if [[ "$grafana_api_call" != *"$app_developer"* ]]; then
+            echo "Grafana does not have $app_developer dashboard."
+            missing_dashboards+=("$app_developer")
           fi
-        done
+          if [[ "$grafana_api_call" != *"$business_user"* ]]; then
+            echo "Grafana does not have $business_user dashboard."
+            missing_dashboards+=("$business_user")
+          fi
+          if [[ "$grafana_api_call" != *"$platform_engineer"* ]]; then
+            echo "Grafana does not have $platform_engineer dashboard."
+            missing_dashboards+=("$platform_engineer")
+          fi
 
-        if [[ ${#missing_alerts[@]} -gt 0 ]]; then
-          echo "Prometheus is missing the following alerts:"
-          printf '%s\n' "${missing_alerts[@]}"
-          echo "Exiting..."
-          exit 1
-        fi
+          if [[ ${#missing_dashboards[@]} -gt 0 ]]; then
+            echo "Grafana is missing the following dashboards:"
+            printf '%s\n' "${missing_dashboards[@]}"
+            echo "Exiting..."
+            exit 1
+          fi
 
-        echo "Prometheus has all alert rules."
+          echo "Grafana contains dashboards $app_developer, $business_user and $platform_engineer. Continuing to Prometheus..."
 
-        # Close Prometheus port-forward
-        kill $prometheus_process_id
-        echo "Stopped port forwarding Prometheus."
+          # Close Grafana port-forward.
+          kill $grafana_process_id
+          echo "Stoppped port forwarding Grafana."
+
+      - name: Port forward Prometheus and check if contains alert rules.
+        run: |
+          kubectl -n monitoring wait --for=condition=ready pod prometheus-k8s-0 --timeout=600s
+          # Port forward Prometheus
+          kubectl -n monitoring port-forward service/prometheus-k8s 9090:9090 &
+          prometheus_process_id=$!
+          echo "Successfully port forwarded Prometheus service."
+
+          sleep 1
+
+          # Make API Call and save response to variable
+          prometheus_api_call=$(curl http://localhost:9090/api/v1/rules)
+
+          # Compare the content in json file with field containing dashboard names.
+
+          readarray -t prometheusrules_policies_missing_alerts < <(yq e '.spec.groups[].rules[].alert' examples/alerts/prometheusrules_policies_missing.yaml)
+          readarray -t slo_availability_alerts < <(yq e '.spec.groups[].rules[].alert' examples/alerts/slo-availability.yaml)
+          readarray -t slo_latency_alerts < <(yq e '.spec.groups[].rules[].alert' examples/alerts/slo-latency.yaml)
+
+          combined_alerts=("${prometheusrules_policies_missing_alerts[@]}" "${slo_availability_alerts[@]}" "${slo_latency_alerts[@]}")
+
+          declare -a missing_alerts=()
+
+          for alert in "${combined_alerts[@]}"; do
+            if [[ "$prometheus_api_call" != *"$alert"* && "$alert" != "null" ]]; then
+              echo "Prometheus does not have $alert rule."
+              missing_alerts+=("$alert")
+            fi
+          done
+
+          if [[ ${#missing_alerts[@]} -gt 0 ]]; then
+            echo "Prometheus is missing the following alerts:"
+            printf '%s\n' "${missing_alerts[@]}"
+            echo "Exiting..."
+            exit 1
+          fi
+
+          echo "Prometheus has all alert rules."
+
+          # Close Prometheus port-forward
+          kill $prometheus_process_id
+          echo "Stopped port forwarding Prometheus."
+
+  deregister-runner:
+    runs-on: ubuntu-latest
+    needs: verify-dashboards-alerts
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Create PEM file
+        run: |
+          echo "${{ secrets.AWS_PEM_KEY }}" > ${{ secrets.AWS_KEY_NAME }}.pem
+          chmod 600 ${{ secrets.AWS_KEY_NAME }}.pem
+
+      - name: Generate Remove Token
+        id: remove_token
+        run: |
+          REPO_OWNER=${{ github.repository_owner }}
+          REPO_NAME=${{ github.event.repository.name }}
+
+          RUNNER_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runners | jq '.runners[] | select(.name=="self-hosted") | .id')
+
+          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runners/$RUNNER_ID
+
+      - name: Terraform Destroy
+        run: terraform destroy -auto-approve -var=aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }} -var=aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} -var=aws_key_name=${{ secrets.AWS_KEY_NAME }}
